logdog:

  # set path to log file
  
  file: /var/log/nginx/access.log

  # this is examples of nginx log entries
  # 127.0.0.1 - - [24/Mar/2016:14:27:17 +0300] "GET / HTTP/1.1" 200 396 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0)

  # define how to extract time chunks 
  # from your log entries:

  # this should perl regexp:
  time_pattern:  '\[(\d+\/\S+\/\d+):(\S+)'

  # this should be posix strftime format
  # see `man strftime`
  time_format:   '%d/%b/%Y %T'

  # check logs for last 5 minutes, 10 hours, 2 days , etc ...
  hitask: '5 minutes'

  # to proper time calculation 
  # need to know a timezone
  timezone: 'Europe/Moscow'

  # I need these lines
  filter: 'HTTP\/\S+?"\s+500\s'

  # group found entries by IP address:
  key_field: '(\S+)'

  # density - is optional parameter
  # show only groups with entries number 
  # more or equal $density
  density: 1


