action: install 
os_url: 
  debian:   https://github.com/nxadm/rakudo-pkg/releases/download/v2017.11/rakudo-pkg-Debian8.9_2017.11-01_amd64.deb
  ubuntu:   https://github.com/nxadm/rakudo-pkg/releases/download/v2017.11/rakudo-pkg-Ubuntu14.04_2017.11-01_amd64.deb
  centos6:  https://github.com/nxadm/rakudo-pkg/releases/download/v2017.11/rakudo-pkg-CentOS7.4-2017.11-01.x86_64.rpm
  centos7:  https://github.com/nxadm/rakudo-pkg/releases/download/v2017.11/rakudo-pkg-CentOS7.4-2017.11-01.x86_64.rpm
  fedora:   https://github.com/nxadm/rakudo-pkg/releases/download/v2017.11/rakudo-pkg-Fedora25-2017.11-01.x86_64.rpm
  alpine:   https://github.com/nxadm/rakudo-pkg/releases/download/v2017.11/rakudo-pkg-Alpine3.6_2017.11-01_x86_64.apk

repo:
  archlinux: https://spider-mario.quantic-telecom.net/archlinux/$repo/$arch

